<?php
$mysql_hostname = 'localhost';
$mysql_username = 'root';
$mysql_password = 'blah4096';
$mysql_database = 'calendar';
$mysql_tablename = 'phpcalendar';
$title = 'PHP-Calendar 0.5';
$header = 'PHP-Calendar';
$bgcolor = '#336699';
$textcolor = 'blue';
$headercolor = 'white';
$headerbgcolor = 'gray';
$tablebgcolor = '#CCCCCC';
$futurecolor = 'white';
$pastcolor = '#CCDDFF';
$nonecolor = 'silver';
$bordercolor = '#339999';
?>